---
  pkgs:
    - gcc
    - git
    - sqlite
    - mongodb

  pip_executable: pip2

  chn_logdir: /var/log/mhn

  mnemosyne_dir: /opt

  hpfeeds_repo: https://github.com/breakfastdub/hpfeeds.git
  ### NEED TO UPDATE THIS TO MASTER
  ### ONCE MASTER HAS THE FORK MERGED
  hpfeeds_version: staging
  hpfeeds_dir: /srv